### ISSUE TITLE
Support for Set/Map

### ISSUE THREAD

**Issue by quicksnap** [yahoo/serialize-javascript#12]
Would you accept a PR for serializing Set/Map?

**Comment by ericf** [comment]
Sure. I'm interested to see how you would rehydrate them…

**Comment by quicksnap** [comment]
Off the top of my head, I think `Set` would be easy enough as `new Set([ /* JSON dump of Set*/ ])` I suppose the same could be done for `Map`, but dehydrating it beforehand as a key/value

**Comment by pimterry** [comment]
For those interested in this, I've opened a PR (#45) that adds Set & Map support, and published it temporarily as a fork at https://www.npmjs.com/package/@httptoolkit/serialize-javascript.

The fork is just so I can start using it straight away in my own projects before it's merged, but you're welcome to use it/test it from there too in the meantime if this is useful to you as well.

**Comment by okuryu** [comment]
Published `serialize-javascript@1.7.0`. Thanks!
