### ISSUE TITLE
BigInt `0n` Throws Error

### ISSUE THREAD

**Issue by WilsontheWolf** [yahoo/serialize-javascript#154]
The BigInt 0n throws an error when serializing, unlike every other BigInt.

![image](https://user-images.githubusercontent.com/33164598/207472900-8b979786-f1f6-4467-b223-8f1d6ed21f62.png)

**Comment by momocow** [comment]
I found this is because `0n` evaluates `true` in this `if` clause and the original value (as a bigint) is returned directly.

https://github.com/yahoo/serialize-javascript/blob/343abd98ff0a3f88f61fca35100762fdd6cb1963/index.js#L86-L88

**Comment by okuryu** [comment]
published v6.0.1.
