### ISSUE TITLE
Deserialize support?

### ISSUE THREAD

**Issue by nicojs** [yahoo/serialize-javascript#20]
How would one go about deserializing a serialized string? I want to use this library to serialize objects that might contain regex's and pass them on to a child process using `childProcess.send`. Therefore i need to deserialize on the other end.

Is this a use case that this library should support? Or is that something that should be done somewhere else?

I guess i could use something like this:

```javascript
function deserialize(serializedData){
  require('vm').runInThisContext('var a = ' + serializedData);
  return a;
}
```

But i don't think its elegant.

Thanks in advance!

**Comment by ericf** [comment]
Yes, you'd need to eval it in some way. The standard use case is that the serialized string of JavaScript is put within an inline `<script>` and evaluated by a browser. To evaluate in Node, you could do what you're saying, or use `eval()`.

**Comment by nicojs** [comment]
Ah yes i just found it.

```javascript
var a  = eval('(' + text + ')');
```

I forgot the parentheses at first. If you do that, eval will see `{` as the start of a code block. 

I will close this issue. Maybe it would be valuable to add an example piece of code to the readme file.

**Comment by ericf** [comment]
> Maybe it would be valuable to add an example piece of code to the readme file.

Sure, if you want to send a PR for that would be great.
