### ISSUE TITLE
feat: option to not serialize functions

### ISSUE THREAD

**Issue by AndersDJohnson** [yahoo/serialize-javascript#32]

**Comment by dehypnosis** [comment]
+1+1+1+1

**Comment by dehypnosis** [comment]
who guys made any forked version?

**Comment by redonkulus** [comment]
Feel free to open a PR for this change and we can review it.

**Comment by okuryu** [comment]
The new option `ignoreFunction` is available in v2.1.0. Thanks!
https://github.com/yahoo/serialize-javascript#optionsignorefunction
