### ISSUE TITLE
Why not serialize undefined?

### ISSUE THREAD

**Issue by MarkKahn** [yahoo/serialize-javascript#35]
Just wondering what the reason to not preserving `undefined` is?

**Comment by aldarund** [comment]
Indeed, why

**Comment by krutzler** [comment]
Hello, 

This employee can no longer access email on this account.  Your email will not be forwarded.

If you have a sales inquiry, please contact sales@yahoo-inc.com

If you require assistance with a legal matter, please contact legal-notices@yahoo-inc.com

Thank you!

**Comment by okuryu** [comment]
Fixed in `serialize-javascript@1.9.0`. Please try to test it, and free to open a new issue if you have any problems.
