### ISSUE TITLE
Document breaking change for 2.0.0

### ISSUE THREAD

**Issue by GriffinSauce** [yahoo/serialize-javascript#67]
The release notes for 2.0.0 only mention a PR which references another issue that _I think_ means this version will include `undefined` values in the output while it didn't before.

It would be helpful to have a clear indication of what the breaking change for the major version is in the releases list.

**Comment by okuryu** [comment]
I have updated the release notes for v2.0.0.
https://github.com/yahoo/serialize-javascript/releases/tag/v2.0.0

**Comment by GriffinSauce** [comment]
Perfect, thanks!
