### ISSUE TITLE
Support bigint

### ISSUE THREAD

**Issue by evilebottnawi** [yahoo/serialize-javascript#76]

**Comment by okuryu** [comment]
Sure. PR welcome.

**Comment by mum-never-proud** [comment]
@okuryu looks like I am in need of this feature can you review this PR?

**Comment by okuryu** [comment]
yup, I take a look! sorry for my delay 😢

**Comment by mum-never-proud** [comment]
no problem :) @okuryu

**Comment by mum-never-proud** [comment]
**ping** @okuryu

**Comment by okuryu** [comment]
released v4.0.0.
https://github.com/yahoo/serialize-javascript/releases/tag/v4.0.0
