### ISSUE TITLE
Pass/Define `space` attribute

### ISSUE THREAD

**Issue by umidbekkarimov** [yahoo/serialize-javascript#8]
It's impossible to change `space` value in `JSON.stringify` method,

It's just hardcoded

```javascript
var SPACE = 2;

module.exports = function serialize(obj) {
    /* ... */
    str = JSON.stringify(obj, function (key, value) {
    /* ... */
    }, SPACE);

```

**Comment by ericf** [comment]
We're having that discussion in #7. Feel free to add your comments to that thread as to why you want this feature. Thanks!
