### ISSUE TITLE
error secure random number generation is not supported by this browser

### ISSUE THREAD

**Issue by RicardoBrito1938** [yahoo/serialize-javascript#84]
Hello, After i updated to the latest version, i started getting this error when starting my react native App, it worked only when i had the debug enabled, after i rolled back to version 3.0.0, it started working again, is anyone facing the same issue after this update?

**Comment by okuryu** [comment]
Hmm. What browsers does this happen in? I would consider giving it a major version and treating it as a breaking change.

**Comment by RicardoBrito1938** [comment]
Hello thanks for the reply, sinceraly i am not sure if It is this package anymore, because the issue started again, so i rolled back some other packages and build started working one more time and seems stable, i Will close the issue,

**Comment by RicardoBrito1938** [comment]
Done
