### ISSUE TITLE
How would you unserialize and serialized object?

### ISSUE THREAD

**Issue by Dindaleon** [yahoo/serialize-javascript#9]
I am passing a serialized object to the client and now I need to unserialize it. Is this possible? If so, how?

**Comment by caridy** [comment]
@Dindaleon the serialization process produces a JS blob, you just need to produce something like:

```
<script>
var MySerializedObject = <...the serialized value...>;
</script>
```

It really depends on the template engine that you use in node to produce your HTML. Additionally, you can produce a JS blob that can be loaded via a `<script src="path/to/my/serialized-blob.js">`.

**Comment by Dindaleon** [comment]
good, thank you!

**Comment by finetype** [comment]
For anyone else looking for an answer to this problem, I've written something for my particular use case, will be publishing to npm soon. https://github.com/finetype/react-serialize
